# general settings for image SR training
name: MambaIRv2_SR_x4
model_type: MambaIRv2Model
scale: 4
num_gpu: 1
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: TrainSet
    type: PairedImageDataset
    dataroot_gt: /home/waas/MambaIR-main/data4/GT/train
    dataroot_lq: /home/waas/MambaIR-main/data4/LR/trainX4
    filename_tmpl: "{}"
    io_backend:
      type: disk

    gt_size: 192          # 显存不够就继续降：112/96（必须能被scale=4整除）
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 6
    dataset_enlarge_ratio: 20
    prefetch_mode: ~

  val:
    name: ValSet
    type: PairedImageDataset
    dataroot_gt: /home/waas/MambaIR-main/data4/GT/val
    dataroot_lq: /home/waas/MambaIR-main/data4/LR/valX4
    filename_tmpl: "{}"
    io_backend:
      type: disk

# network structures
network_g:
  type: MambaIRv2
  upscale: 4
  in_chans: 3
  img_size: 64
  img_range: 1.0
  embed_dim: 174
  d_state: 16
  depths: [6, 6, 6, 6, 6, 6]
  num_heads: [6, 6, 6, 6, 6, 6]
  window_size: 16
  inner_rank: 64
  num_tokens: 128
  convffn_kernel_size: 5
  mlp_ratio: 2.0
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

  # === wavelet explicit modeling ===
  wavelet_level: 1          # 0(off)/1/2
  use_dfmb_lite: true
  use_feb: false
  feb_scale_init: 0.0
  wav_hidden_ratio: 1.0
  wav_kernel_size: 3
  wav_scale_init: 0.05

# path (只放预训练/断点就够，其他路径 BasicSR 会自动生成 experiments/*)
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [125000, 200000, 225000, 237500]
    gamma: 0.5

  total_iter: 250000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  # ===== your new losses =====
  hf_loss_weight: 0.0
  hf_on_y: false
  fft_loss_weight: 0.0
  fft_on_y: false

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true

    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
